[package]
name = "tty"
version = "0.2.0"
authors = ["Mickaël Salaün <mickael.salaun@ssi.gouv.fr>"]
description = "Create and use pseudoterminal"
repository = "https://github.com/stemjail/tty-rs"
readme = "README.md"
keywords = ["linux", "terminal", "pty", "tty"]
license = "LGPL-3.0"
exclude = [".gitignore"]

[dependencies]
fd = "*"
termios = "*"
