[project]
name = "pty"
version = "0.1.0"
authors = ["Mickaël Salaün <mickael.salaun@ssi.gouv.fr>"]
description = "Create and use pseudoterminal"
repository = "https://github.com/stemjail/pty-rs"
readme = "README.md"
keywords = ["linux", "terminal", "tty"]
license = "LGPL-3.0"

[dependencies.termios]
path = "../termios.rs"
